name: MacOS (Clang)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS_clang:
    runs-on: macos-11
    strategy:
      matrix:
        clangver: [ "11.0", "12.0", "13.0" ]
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21.x'

#      - name: Set up clang
#        uses: egor-tensin/setup-clang@v1
#        with:
#          version: ${{ matrix.clangver }}
#          platform: x64

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clangver }}

      - uses: actions/checkout@v2

      - name: Make build folder
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -- -j4

      - name: Test
        working-directory: ${{github.workspace}}/build/tests/
        run: ./tileson_tests --order rand